// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7tQXD6Otj-KLWC4tToeva-WNeZLk3PBE',
    appId: '1:1001594824531:web:667d68fb57d5d6fb9ea3a6',
    messagingSenderId: '1001594824531',
    projectId: 'quiz-app-30dc1',
    authDomain: 'quiz-app-30dc1.firebaseapp.com',
    storageBucket: 'quiz-app-30dc1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYDD2RU4WnKM_dzxFn6AYArY--Le5P7rI',
    appId: '1:1001594824531:android:7ca6c8d1c6e462e99ea3a6',
    messagingSenderId: '1001594824531',
    projectId: 'quiz-app-30dc1',
    storageBucket: 'quiz-app-30dc1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAi3dRoj1C731jGxcB3eBWRAPt4iueFgEc',
    appId: '1:1001594824531:ios:96f2ca79abc5d7969ea3a6',
    messagingSenderId: '1001594824531',
    projectId: 'quiz-app-30dc1',
    storageBucket: 'quiz-app-30dc1.appspot.com',
    iosClientId: '1001594824531-5rce4eh02ll7ldigat6jlef44k8cogvc.apps.googleusercontent.com',
    iosBundleId: 'com.codefox.quizzle',
  );
}
